//RESTClient allows you to call a REST API directly from VSCode; Postman is an alternative
GET http://localhost:3000/users/get
//GET is a REST verb, describes the action
###

POST http://localhost:3000/users/create
//Tells the server we are sending JSON to it
Content-Type: application/json

{
    "fName": "Chris",
    "lName": "Moreno",
    "userEmail": "cjm6771@psu.edu",
    "userName": "cjm6771",
    "password": "L10n$"
}

###

PUT http://localhost:3000/users/update/
Content-Type: application/json

{
    "password": "It$Wack"
}

###

DELETE http://localhost:3000/users/delete/60f72f2e0f6360f51d1b4aac